gh_actions initial config test 4

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -31,7 +31,7 @@ jobs:
         if: success()
         run: echo "Build succeeded!"
 
-      - name: Notify Build failure
+      - name: Notify build failure
         if: failure()
         run: echo "Build failed!"
 
@@ -60,34 +60,40 @@ jobs:
           SSH_HOST: ${{ secrets.SSH_HOST }}
 
         run: |
+          set -e
           ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
             echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u e-libro --password-stdin
 
+            # Stop and remove the existing container if it exists
             if [ \$(docker ps -a -q -f name=e-libro-api) ]; then
-              docker stop e-libro-api
-              docker rm e-libro-api
+              docker rm -f e-libro-api
             fi
 
+            # Remove the existing image if it exists
             if [ \$(docker images -q ghcr.io/e-libro/e-libro-api:latest) ]; then
-              docker rmi ghcr.io/e-libro/e-libro-api:latest
+              docker rmi -f ghcr.io/e-libro/e-libro-api:latest
             fi
 
+            # Pull the latest image
             docker pull ghcr.io/e-libro/e-libro-api:latest
 
+            # Create the environment file securely
             echo "DB_URL=$DB_URL" > ~/.env.production.api
             echo "PORT=$PORT" >> ~/.env.production.api
             echo "CORS_ORIGIN=$CORS_ORIGIN" >> ~/.env.production.api
             echo "ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET" >> ~/.env.production.api
             echo "REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET" >> ~/.env.production.api
             echo "ENCRYPTION_SECRET_KEY=$ENCRYPTION_SECRET_KEY" >> ~/.env.production.api
-                        
+            chmod 600 ~/.env.production.api
+
+            # Start the new container
             docker run -d --name e-libro-api --env-file ~/.env.production.api -p 8081:8081 ghcr.io/e-libro/e-libro-api
           EOF
 
-      - name: Notify build success
+      - name: Notify deployment success
         if: success()
-        run: echo "Build succeeded!"
+        run: echo "Deployment succeeded!"
 
-      - name: Notify build failure
+      - name: Notify deployment failure
         if: failure()
-        run: echo "Build failed!"
+        run: echo "Deployment failed!"
